name: GH-CI

on: [push]

jobs:
  gh-ci:
    runs-on: ubuntu-latest
    name: PHP Validation
    steps:
    - uses: actions/checkout@v3
    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
    - name: PHP Composer
      uses: php-actions/composer@v6
    - name: PHPStan
      uses: php-actions/phpstan@v3
      with:
        path: ./
