on: [push]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    name: PHPStan (php-actions)
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - uses: php-actions/phpstan@v3
      with:
        command: composer install
        configuration: tests/ci/phpstan.neon
        path: .